# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
torch.rand(7,7)

tensor([[0.3416, 0.4945, 0.5983, 0.7718, 0.8070, 0.3901, 0.2231],
        [0.3607, 0.8744, 0.6931, 0.1067, 0.7328, 0.3877, 0.6770],
        [0.6638, 0.6865, 0.8591, 0.9107, 0.1988, 0.8669, 0.4109],
        [0.4844, 0.1857, 0.8810, 0.0880, 0.7824, 0.6066, 0.2536],
        [0.8808, 0.1883, 0.1277, 0.5062, 0.2294, 0.5717, 0.1309],
        [0.1361, 0.4470, 0.6394, 0.8771, 0.8951, 0.1257, 0.8120],
        [0.8008, 0.0417, 0.3290, 0.2225, 0.1312, 0.2990, 0.8919]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [20]:
# Create another random tensor
tensor_1 = torch.randn(1,7)
tensor_2 = torch.randn(1,7)

# Perform matrix multiplication 
torch.squeeze(torch.matmul(tensor_1, tensor_2.T))

tensor(0.5942)

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [15]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_1 = torch.rand(1, 7)
tensor_2 = torch.rand(1, 7)

# Matrix multiply tensors
tensor_1, tensor_2,  torch.matmul(tensor_1, tensor_2.T)

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]]),
 tensor([[0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689]]),
 tensor([[1.1173]]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU
torch.cuda.manual_seed(0)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [22]:
# Set random seed
torch.manual_seed(0)
torch.cuda.manual_seed(0)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
tensor_1 = torch.rand(2, 3, device = device)
tensor_2 = torch.rand(2, 3, device = device)

tensor_1 @ tensor_2.T


tensor([[0.9722, 0.6174],
        [0.6292, 0.4455]])


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [23]:
# Perform matmul on tensor_A and tensor_B
mul = torch.squeeze(tensor_1 @ tensor_2.T)
mul


tensor([[0.9722, 0.6174],
        [0.6292, 0.4455]])

### 8. Find the maximum and minimum values of the output of 7.

In [26]:
# Find max
print(mul.max())
# Find min
print(mul.min())

tensor(0.9722)
tensor(0.4455)


### 9. Find the maximum and minimum index values of the output of 7.

In [27]:
# Find arg max
print(mul.argmax())

# Find arg min
print(mul.argmin())

tensor(0)
tensor(3)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [28]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_squeeze = torch.squeeze(tensor)

# Print out tensors and their shapes
tensor, tensor_squeeze, tensor_squeeze.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))