In [1]:
!nvidia-smi

Mon Jul 24 13:38:05 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 462.62       Driver Version: 462.62       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 1650   WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   54C    P0    15W /  N/A |    297MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch

In [3]:
torch.__version__

'2.0.0+cpu'

In [10]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [15]:
print(scalar.ndim)
print(scalar.shape)

0
torch.Size([])


In [25]:
ts = torch.Tensor(7, 3)
ts

tensor([[5.9694e-39, 7.0714e-39, 7.1633e-39],
        [8.9082e-39, 8.9082e-39, 1.0194e-38],
        [9.1837e-39, 4.6837e-39, 9.2755e-39],
        [1.0837e-38, 8.4490e-39, 7.6224e-39],
        [1.0194e-38, 1.0469e-38, 9.2755e-39],
        [8.9082e-39, 9.9184e-39, 9.0000e-39],
        [1.0561e-38, 1.0653e-38, 4.1327e-39]])

In [18]:
ts.ndim

2

In [19]:
ts.shape

torch.Size([7, 3])

In [22]:
scalar.item()

7

In [23]:
ts[1, 2].item()

1.0193878802084993e-38

In [50]:
ts = torch.empty(7, 3, dtype=torch.int32)

In [51]:
ts

tensor([[2131828032,        523, 2131823664],
        [       523, 2131825120,        523],
        [2131822832,        523, 2131824288],
        [       523, 2131821792,        523],
        [2131823040,        523, 2131825536],
        [       523, 2131824496,        523],
        [2131827408,        523, 2131825328]], dtype=torch.int32)

In [60]:
torch.rand(size=(3,2)).shape

torch.Size([3, 2])

In [158]:
device = "cuda"
x = torch.tensor([[1,4,4], [2,3,4]])

In [71]:
torch.matmul(x.T, w)

tensor([[ 5, 14,  9],
        [10, 26, 21],
        [12, 32, 24]])

In [72]:
import numpy as np

In [148]:
w = torch.tensor([[1,2,3], [2,6,3]])
w

tensor([[1, 2, 3],
        [2, 6, 3]])

In [151]:
a = w.numpy()
w = a + 1
w


AttributeError: 'numpy.ndarray' object has no attribute 'numpy'

In [152]:
a = np.array([1,2,3])
w = torch.from_numpy(a)

In [153]:
a = a + 1
w

tensor([1, 2, 3], dtype=torch.int32)

In [4]:
cuda0 = torch.device('cuda:1')

In [8]:
cuda0
torch.tensor(1, device=cuda0)

AssertionError: Torch not compiled with CUDA enabled

In [6]:
a = torch.tensor([[1,2,3], [4,5,6]])
b = torch.tensor([[1,2], [3,2]])

c = torch.hstack([a, b])
c.shape

torch.Size([2, 5])

In [111]:
c.permute(dims=(1,0)).shape


torch.Size([5, 2])

In [113]:
x = torch.arange(1., 8.)
x

tensor([1., 2., 3., 4., 5., 6., 7.])

In [114]:
torch.stack([x, x, x, x], dim=0)

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

In [119]:
torch.stack([x, x, x, x], dim=1).squeeze()

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [120]:
x_reshaped = x.reshape(1, 7)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7.]])

In [121]:
x_reshaped.shape

torch.Size([1, 7])

In [122]:
x_reshaped.squeeze().

tensor([1., 2., 3., 4., 5., 6., 7.])

In [127]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x_in = torch.Tensor(10, 2)
output = linear(x_in)
print(f"Input shape: {x_in.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([10, 2])

Output:
tensor([[ 0.5224,  0.0958,  0.3410, -0.0998,  0.5451,  0.1045],
        [ 0.5224,  0.0958,  0.3410, -0.0998,  0.5451,  0.1045],
        [ 0.5224,  0.0958,  0.3410, -0.0998,  0.5451,  0.1045],
        [ 0.5224,  0.0958,  0.3410, -0.0998,  0.5451,  0.1045],
        [ 0.5224,  0.0958,  0.3410, -0.0998,  0.5451,  0.1045],
        [ 0.5224,  0.0958,  0.3410, -0.0998,  0.5451,  0.1045],
        [ 0.5224,  0.0958,  0.3410, -0.0998,  0.5451,  0.1045],
        [ 0.5224,  0.0958,  0.3410, -0.0998,  0.5451,  0.1045],
        [ 0.5224,  0.0958,  0.3410, -0.0998,  0.5451,  0.1045],
        [ 0.5224,  0.0958,  0.3410, -0.0998,  0.5451,  0.1045]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([10, 6])
