## Cross Entropy 

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Softmax Function

$$ Softmax = \frac{e^x}{\sum_{t = 1}^{c}{e^x}} $$

In [2]:
x = np.array([5,2,1,3])

In [4]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

In [5]:
softmax(x)

array([0.83095266, 0.0413707 , 0.01521943, 0.11245721])

## Likelihood

$$    L(\theta) = \prod_{i = 1}^{m}{\prod_{k = 1}^{c}{P(Y_i \| X_i, \theta_i)}} = \prod_{i = 1}^{m}{\prod_{i = 1}^{c}{h_{\theta_i}^{1\{Y = X_i\}}}}    $$

$$LL(\theta) = \sum_{i = 1}^{c}{1\{Y = X_i\}log(h_{\theta_i})}$$

### Change to one hot vector => Categorical Cross Entropy
$$ LL(\theta) = \sum_{i = 1}^{c}{\textbf{yi} \dot log(\textbf{h_{\theta_i}})} $$

In [8]:
o1 = np.array([5,3,1,6,2])

y_one_hot1 = np.array([0,0,0,1,0])
y_hat1 = softmax(o1)
y_hat1

array([0.25499017, 0.03450917, 0.00467031, 0.69313514, 0.01269521])

In [9]:
o2 = np.array([7,3,2,1,4])

y_one_hot2 = np.array([1,0,0,0,0])
y_hat2 = softmax(o2)
y_hat2

array([0.92822982, 0.01700112, 0.00625436, 0.00230085, 0.04621384])

In [16]:
# loss function = sum(y_i * log(y^hat)) == y_i : one-hot vector
Loss = - (np.dot(y_one_hot1, np.log(y_hat1)) + np.dot(y_one_hot2, np.log(y_hat2)))
Loss

0.4410062116228437

In [11]:
Loss

array([0.92822982, 0.        , 0.        , 0.69313514, 0.        ])