<h1 style="text-align: center">Numpy </ h3>

### 1. Write a NumPy program to print the NumPy version on your system.

In [1]:
import numpy as np

In [2]:
np.version.version

'1.21.5'

### 2. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.

In [3]:
my_list = [1,2,5,7,2]
np_list = np.array(my_list)
np_list

array([1, 2, 5, 7, 2])

### 3. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [10]:
np.arange(2, 11).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

### 4. Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.

In [17]:
x = np.zeros(10, dtype=int)
x[6] = 11

In [18]:
x

array([ 0,  0,  0,  0,  0,  0, 11,  0,  0,  0])

### 5. Write a NumPy program to create an array with values ranging from 12 to 38.

In [43]:
def RangeValue(x: int, y: int) -> np.ndarray:
    if x > y:
        raise RuntimeError("x must be less than y")
    return np.arange(x, y)

In [44]:
RangeValue(3,4)

array([3])

In [45]:
RangeValue(3,3)

array([], dtype=int32)

In [46]:
RangeValue(3, 2)

RuntimeError: x must be less than y

### 6. Write a NumPy program to reverse an array (the first element becomes the last).

In [41]:
np_list

array([1, 2, 5, 7, 2])

In [48]:
np.flip(np_list)

array([2, 7, 5, 2, 1])

### 7.  Write a NumPy program to convert an array to a floating type.

In [49]:
np_list.astype(float)

array([1., 2., 5., 7., 2.])

### 8. Write a NumPy program to create a 2D array with 1 on the border and 0 inside.

In [80]:
def Custom2DArray(x: int, y: int) -> np.ndarray:
    custom_array = np.zeros(x * y).reshape(x, y)
    custom_array[0] = np.ones(y)
    custom_array[-1] = np.ones(y)
    
    for index in range(1, x - 1):
        custom_array[index][0] = 1
        custom_array[index][-1] = 1
        
    return custom_array

In [82]:
Custom2DArray(1, 4)

array([[1., 1., 1., 1.]])

### 9. Write a NumPy program to add a border (filled with 0's) around an existing array.

In [120]:
def Padding(arr: np.ndarray) -> np.ndarray:
    x, y = arr.shape
    x, y = x + 2, y + 2
    padding_array = np.zeros(x * y).reshape(x, y)
    
    for i in range(1, y - 1):
        padding_array[i][1:-1] = arr[i - 1]
        
    return padding_array

In [124]:
Padding(np.arange(3 * 3).reshape(3,3))

array([[0., 0., 0., 0., 0.],
       [0., 0., 1., 2., 0.],
       [0., 3., 4., 5., 0.],
       [0., 6., 7., 8., 0.],
       [0., 0., 0., 0., 0.]])

In [128]:
x = np.ones(4 * 4).reshape(4,4)